#+title: p-snow's home configurations

This repository holds a collection of my home-use software tweaks stored in the form of literate configuration, mainly focused on Linux and Emacs. All configurations are consolidated in [[file:dotfiles.org][dotfiles.org]], and [[https://p-snow.org/config/dotfiles.html][an intelligible website]] derived from the file is also available.

#+begin_src text :exports none
About:

A collection of home-use software tweaks stored in the form of literate configuration, mainly focused on Linux and Emacs
#+end_src

#+begin_src text :exports none
Website:

https://p-snow.org/config/dotfiles.html
#+end_src

* Literate Configuration
:PROPERTIES:
:CREATED:  [2024-03-30 Sat 14:07]
:END:

Literate configuration is a method derived from Literate programming proposed by D. Knuth, where configurations are located alongside their documentation. In [[file:dotfiles.org][dotfiles.org]], each configuration is diffused into an appropriate org entry and can be extracted to viable dotfiles.

** Dotfile Extraction

Basically, the set of configurations is woven together and tailored specifically for me ([[https://github.com/p-snow][p-snow]]) as the sole user. However, anyone can extract dotfiles by using the following incantation:

: make tangle

- extraction destination

  With the command above, all dotfiles will be located under the path below, which is my preference but can be customized by modifying the following line in [[file:tangle.el][tangle.el]].

  : (setq tangle/home "~/data/ghq/github.com/p-snow/dotfiles/")

* Salient Contexts
:PROPERTIES:
:CREATED:  [2024-03-30 Sat 17:32]
:END:

The total line count of my configuration is gigantic. It's tough for visitors to find their interests quickly, so I have selected some salient configurations below, which are very unique compared to others.

** [[https://p-snow.org/config/dotfiles.html#gnu-emacs][Emacs Configuration]]
:PROPERTIES:
:CREATED:  [2024-03-30 Sat 17:39]
:END:

Emacs is more than just an editor for me. It is a complete environment where I comfortably read, write, code, and create. My configuration demonstrates how customizable and adaptable Emacs can be.

*** Japanese Settings
:PROPERTIES:
:CREATED:  [2024-03-30 Sat 17:50]
:END:

I am Japanese, and my first language is Japanese. The "[[https://p-snow.org/config/dotfiles.html#emacs-language][Language section]]" demonstrates how to set up the language environment, locale, and coding systems for non-English speakers, especially Japanese. The "[[https://p-snow.org/config/dotfiles.html#emacs-fontset][Fontset section]]" shows how to create Emacs fontsets using my favorite Japanese fonts, [[https://moji.or.jp/ipafont/ipafontdownload/][IPA font]].

*** as Visual Aid
:PROPERTIES:
:CREATED:  [2024-04-26 Fri 15:13]
:END:

I am visually impaired; my visual acuity is 20/400, or something lower. Thanks to Emacs's customizability, I can read, write, and edit text flawlessly with a huge font. The "[[https://p-snow.org/config/dotfiles.html#emacs-face][Face section]]" reveals how to do that.
