(require 'org)
(require 'ob-core)
(require 'ob-shell)

(load-file (expand-file-name "./org-babel-config.el"))
(remove-hook 'org-babel-pre-tangle-hook
             'save-buffer)

(let* ((current-dir (expand-file-name "."))
       (org-files (directory-files current-dir nil "\\.org$"))
       (python-indent-guess-indent-offset nil)
       (org-id-locations-file nil))
  (mapc (lambda (org-file)
          (org-babel-lob-ingest org-file))
        org-files)
  (dolist (org-file org-files)
    (unless (member org-file '("README.org" "index.org"))
      (with-current-buffer (find-file-noselect org-file)
        (let ((default-directory (org-entry-get nil "tangle-dest" t)))
          (org-decrypt-entries)
          (org-babel-tangle))))))
