#+title: オレの自慢のタスク「アクティブクリーニング」
#+date: <2024-11-09 Sat 15:29>
#+description:
#+filetags: task

#+SETUPFILE: diary/header

{{{preview-begin}}}
定期的な掃除というものが苦手です。どんなにキレイにしても精魂込めて磨き上げても、月日が経てば元の木阿弥。こんなことに時間かけるんだったxxxの方が、とか意識下では考えて気がのらなくなるのかもしれません。そんな状況がとあるタスク管理手法で少しだけ改善したのでそのことについて書いてみたいとおもいます。
{{{preview-end}}}

本題に入る前にまず私の性格というもののあらましを言っておかなければなりません。こんなティンカラー日記なるものを好んで書いているくらいなので想像に難くないとはおもいますが、私は、はい、凝り性です。もう少し詳しく書くならば、「その瞬間に自分が興味をもてるものに関しては」かなりのコダワリをもって事に当たることができます。局所的な「攻めタイプ」と言えるのかもしれません。

一方で「定期的な掃除」というタスクは「守り」に分類されるでしょう。浴槽洗浄にしてもキッチンシンクまわりの清掃にしてもやることは決まっていて一定期間それらをサボると惨めな結果になる。これらに対処するタスク管理としては、個々の掃除対象をそれぞれ別のタスクとして定義して一定期間がきたら実行するように促すHabitタスクにする、みたいな案が浮かぶかもしれませんが(実際、昔の私がそうでした)、それをしてしまうと特に私のような性格の人間には耐えられない状況になってきます。

何と言うか独特の息苦しさがあるというか、ずっと門番のように何かを守る立場に立たされている感じがしてしまうのです。一般的にタスク管理においてゾンビタスク的なものが堆積してしまってタスク管理全般がイヤになるという話にも通じている気がします。

では私はどうしたか。すべての掃除項目をひとつのタスクにしました。そしてどの箇所の掃除をしてもそのタスクは実行済み扱いにして一定期間はタスクリストには上がらないようにします。タスク名はズバリ「アクティブクリーニング」。このように細かいタスクをバルク化してひとつにすると、あら不思議、守りのタスクが攻めのメンタルで攻略可能となったのです。もちろんツッコミどころは満載でしょう。しかし掃除ていどのことはこのくらいの構えで対応していいカテゴリだとおもいます。

自分の日常のどんなタスクがバルク化可能かを考えて実行すると、タスク管理において少し肩の荷をおろせるかもしれません。
